[package]
name = "mruby-polars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minutus = { path = "../../minutus" }
polars = "0.23.1"

[lib]
crate-type = ["staticlib"]
