[package]
name = "mruby-polars"
version = "0.1.0"
edition = "2021"

# workaround ignoring minutus's workspace
[workspace]

[dependencies]
minutus = { path = "../../minutus", features = ["mruby_3_2_0"] }
polars = "0.23.1"

[lib]
crate-type = ["staticlib"]
