[package]
name = "minutus-mruby-build-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bytes = "*"
tar = "*"
reqwest = { version = "*", features = ["blocking"] }
flate2 = "*"
