[package]
name = "minutus"
version = "0.1.0"
edition = "2021"

[build-dependencies]
minutus-mruby-build-utils = { path = "../minutus-mruby-build-utils" }
anyhow = "1.0"
bindgen = "*"
cc = "*"

[dependencies]
minutus-macros = { path = "../minutus-macros" }
minutus-macros-type = { path = "../minutus-macros-type" }
minutus-mruby-build-utils = { path = "../minutus-mruby-build-utils" }

[features]
mruby_3_1_0 = []
mruby_2_1_2 = []
mruby_master = []
link_mruby = []
