[package]
name = "custom-mruby"
version = "0.1.0"
edition = "2021"

# workaround ignoring minutus's workspace
[workspace]

[build-dependencies]
minutus = { path = "../../minutus" }

[dependencies]
minutus = { path = "../../minutus", features = ["mruby_3_2_0"]  }
