name: Lint

on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Lint README.md
        uses: avto-dev/markdown-lint@v1
        with:
          args: "README.md"
          config: ".markdownlint.config.json"
