name: Test

on: [push, pull_request]
jobs:
  cargo_test:
    name: cargo test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo test --workspace

  integration_test:
    name: run all integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: CLEAN=true rake run_all
